[workspace]
members = [
    "algorithms",
    "data_structures",
    "rust",
    "practice",
    "leetcode",
    "design_patterns",
    "low-level",
    "projects/solana",
    "projects/pulsar-take-home",
    "projects/one_brc",
    "projects/custom-macros",
    "hackerrank"
]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.49.0", features = ["full"] }
anchor-lang = "0.32.1"

