[package]
name = "rust_specifics"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
mockall = "0.13.1"
reqwest = { version = "0.12.15", features = ["blocking"]}
tokio = { version = "1.45.0", features = ["full"] }

[features]
streaming = []
default = []